name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: testdockergema/tmc-todolist-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: SSH into VPS and deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        script: |
          docker pull testdockergema/tmc-todolist-app:latest
          docker stop todolist-app || true
          docker rm todolist-app || true
          docker run -d --name todolist-app -p 3005:3005 testdockergema/tmc-todolist-app:latest
